config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update, :show]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:update]
    resources :order_details, only: [:update]
    resources :works, only: [:update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
get "about" => "public/homes#about"

  scope module: :public do
    root to: "homes#top"
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index,:update,:show,:create,:destroy]
    delete '/cart_items' => 'cart_items#destroy_all'
    post '/orders/comfirm' => 'orders#comfirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  
  validates :item_name, presence: true
  validates :item_text, presence: true
  validates :no_tax_price, presence: true
  validates :genre, presence: true


  def get_image(width, height)
      unless image.attached?
        file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
        image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      image.variant(resize_to_limit: [width, height]).processed
  end




        #消費税込み
    def on_tax_price
      tax_rate = 1.1
      (self.no_tax_price * tax_rate).floor
    end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
     redirect_to admin_item_path(@item)
    else
      render :new
    end
  end


  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end


  private
  def item_params
    params.require(:item).permit(:item_name, :item_text, :no_tax_price, :sale_status, :genre_id, :image)
  end
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mt-5">
<h2 class=>商品編集</h2>
</div>
</div>
<div class="container">
  <div class="row justify-content-center">
<%= form_with model:@item,url:admin_item_path,local:true do |f| %>

<table>
  <tbody>
    <tr>
    <th>商品画像</th>
    <td><%= f.file_field :image %></td>
    </tr>
    <tr>
    <th>商品名</th>
    <td><%= f.text_field :item_name, class: "form-control" %></td>
    </tr>
    <tr>
    <th>商品説明</th>
    <td><%= f.text_area :item_text, class: "form-control" %></td>
    </tr>
    <tr>
    <th>ジャンル</th>
    <td><%= f.collection_select :genre_id, Genre.all ,:id, :genre, include_blank: "--選択してください--" %></td>
    </tr>
    <tr>
    <th>税抜価格</th>
    <td><%= f.text_field :no_tax_price, class: "form-control" %></td>
    </tr>
    <tr>
    <th>販売ステータス</th>
    <td><%= f.select :sale_status,[["販売中",true],["販売停止中",false]],include_blank: "選択して下さい" %></td>
    </tr>
  </tbody>
</table>
<div class="text-center">
<%= f.submit "変更を保存",class: "btn btn-primary text-right" %>
</div>
<% end %>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-5">
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5">
<h2>商品一覧</h2>
<div class="text-right mb-2">
  <%= link_to "新規登録" ,new_admin_item_path, class:"btn btn-lg btn-success" %>
</div>
<table class="table ">
  <thead class="bg-lite">
    <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜価格</th>
    <th>ジャンル</th>
    <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @items.each do |item| %>
    <td><%= item.id %></td>
    <td><%= link_to item.item_name, admin_item_path(item) %></td>
    <td><%= item.no_tax_price %></td>
    <td><%= item.genre.genre %></td>
    <td><% if item.sale_status %>
        <span class="text-success">販売中</span>
        <% else %>
        販売停止中
        <% end %>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @items %>
  </div>
</div>
</div>

app/views/admin/items/new.html.erb
<div class ="container">
<div class="row">
  <div class="col-md-5 mt-5">
    <h2>商品新規登録</h2>
  </div>
</div>
</div>
<div class="container mt-5">
<div class="row justify-content-center">
<%= form_with model:@items,url:admin_items_path,local:true do |f| %>
<table>
  <tbody>
    <tr>
    <th>商品画像</th>
    <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
    <tr>
    <th>商品名</th>
    <td><%= f.text_field :item_name, class: "form-control" %></td>
    </tr>
    <tr>
    <th>商品説明</th>
    <td><%= f.text_area :item_text, class: "form-control" %></td>
    </tr>
    <tr>
    <th>ジャンル</th>
    <td><%= f.collection_select :genre_id, Genre.all ,:id, :genre, include_blank: "--選択してください--" %></td>
    <tr>
    <th>税抜価格</th>
    <td><%= f.text_field :no_tax_price, class: "form-control" %></td>
    </tr>
    <tr>
    <th>販売ステータス</th>
    <td><%= f.select :sale_status,[["販売中",true],["販売停止中",false]],include_blank: "選択して下さい" %></td>
    </tr>
  </tbody>
  </table>
  <%= f.submit "新規登録" , class: "btn btn-primary pull-right" %>
  <% end %>
  </div>
  </div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 mt-5">
<h2>商品詳細</h2><br>
<%= image_tag @item.get_image(250, 250) %>
</div>
<br><br><br><br>
<div class="col-md-8 mt-5">
<table class="table">
<tbody>
  <tr></tr>
  <td>商品名</td>
  <td><%= @item.item_name %></td>
  </tr>
  <tr>
  <td>商品説明</td>
  <td><%= @item.item_text %></td>
  </tr>
  <tr>
  <td>ジャンル</td>
  <td><%= @item.genre.genre %></td>
  </tr>
  <tr></tr>
  <td>税抜価格</td>
  <td><%= @item.no_tax_price %></td>
  </tr>
  <tr>
  <td>販売ステータス</td>
  <td><% if @item.sale_status %>
        <p class="text-success">販売中</p>
        <% else %>
        販売停止中
        <% end %>
  </td>
  </tr>
</tbody>
</table>
<%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
</div>
</div>
</div>