config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update, :show]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:update]
    resources :order_details, only: [:update]
    resources :works, only: [:update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
get "about" => "public/homes#about"

  scope module: :public do
    root to: "homes#top"
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index,:update,:show,:create,:destroy]
    delete '/cart_items' => 'cart_items#destroy_all'
    post '/orders/comfirm' => 'orders#comfirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  #is_deleteがfalseなら、trueを
  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer)
  end 
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/views/admin/customers/edit.html.erb
<div class="container">
<div class="row mt-5">
<h2><%= (@customer.last_name + @customer.first_name) %>さんの会員情報編集</h2>
</div>
</div>
<%= form_for(@customer, url: admin_customer_path(@customer)) do |f| %>
<div class="container">
  <div class="row">
<table class="row table">
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= f.text_field :last_name,  class:"form-control" %> <%= f.text_field :first_name,  class:"form-control" %></td>
  </tr>
  <tr>
    <th>フリガナ</th>
    <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
  </tr>
  <tr>
    <th>郵便番号</th>
    <td><%= f.text_field :postal_code %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= f.text_field :address %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= f.text_field :telephone_number %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td>
      　<%= f.radio_button :is_deleted, false %>
      　<%= f.label :is_deleted, "有効"%>
      　<%= f.radio_button :is_deleted, true %>
      　<%= f.label :is_deleted, "退会"%>
    </td>
  </tr>
</table>
<%= f.submit "変更を保存する" ,class: "btn btn-success " %>
<% end %>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mt-5">
<h2>会員一覧</h2>
</div>
</div>
<div class="container">
<div class="row">
<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer) %></td>
      <td><%= customer.email %></td>
      <td><% if customer.is_deleted %>
              <span class="label label-danger">退会</span>
            <% else %>
              <span class="text-success">有効</span>
            <% end %>
      </td>
    </tr>
    <% end %>
</tbody>
</table>
</div>
</div>
<div class="text-center">
<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
<div class="row mt-5">
<h2 class="mb-5"><%= (@customer.last_name + @customer.first_name) %>さんの会員詳細</h2>

<table class="row table">
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= @customer.last_name %><%= @customer.first_name %></td>
  </tr>
  <tr>
    <th>フリガナ</th>
    <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <th>郵便番号</th>
    <td><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @customer.address %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td><% if @customer.is_deleted %>
        <span class="label label-danger">退会</span>
      <% else %>
        <span class="label label-primary">有効</span>
      <% end %>
    </td>
  </tr>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-5" %>
<%= link_to "注文履歴一覧を見る",admin_root_path, class: "btn btn-primary" %>
</div>
</div>