config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update, :show]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:update]
    resources :order_details, only: [:update]
    resources :works, only: [:update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
get "about" => "public/homes#about"

  scope module: :public do
    root to: "homes#top"
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index,:update,:show,:create,:destroy]
    delete '/cart_items' => 'cart_items#destroy_all'
    post '/orders/comfirm' => 'orders#comfirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_detail = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      if order.order_status == "payment_confirmation"
        order.order_details.each do |order_detail|
          order_detail.update(production_status: 1)
        end
      end
      redirect_to admin_order_path(order.id)
    end
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

  # binding.pry

app/views/admin/orders/show.html.erb
<div class="container-fluid px-5 mt-5">
  <div class="row">
    <div>
      <h2>注文履歴詳細</h2>
    </div>
  </div>
  <div class="row mt-3">
    <div  class="col-sm-10">
      <table class="table table-borderless">
        <tr>
          <th class="col-sm-2">購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer_id) do %>
              <%= @order.customer.last_name + @order.customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="col-sm-2">注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th class="col-sm-2">配送先</th>
          <td>〒<%= @order.shipping_postcode + ' ' + @order.shipping_address %><br><%= @order.shipping_name %></td>
        </tr>
        <tr>
          <th class="col-sm-2">支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th class="col-sm-2 align-middle">注文ステータス</th>
          <td class="form-inline">
            <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
              <%= f.select:order_status, Order.order_statuses_i18n.invert, {}, class:"form-control" %>
              <%= f.submit "更新", class:"btn btn-success ml-4" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-sm-8">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col" style="width: 35%">商品名</th>
            <th scope="col" style="width: 20%">単価（税込）</th>
            <th scope="col" style="width: 10%">数量</th>
            <th scope="col" style="width: 10%">小計</th>
            <th colspan="2"  scope="col" style="width: 25%">制作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% total = 0 %>
          <% @order_detail.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.item_name %></td>
              <td><%= order_detail.purchase_price %>円</td>
              <td><%= order_detail.quantity %>個</td>
              <td><%= order_detail.purchase_price * order_detail.quantity %>円</td>
              <%= form_with model: order_detail, url: admin_work_path(order_detail.id), method: :patch do |f| %>
                <td><%= f.select :production_status, OrderDetail.production_statuses_i18n.invert, {}, class:"form-control" %></td>
                <td><%= f.submit '更新', class:"btn btn-success" %></td>
                <% total += order_detail.purchase_price * order_detail.quantity %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div  class=" col-sm-3 offset-sm-1 align-self-end">
      <table class="table table-borderless">
        <tr><th>商品合計</th><td><%= total %>円</td></tr>
        <tr><th>送料</th><td><%= @order.postage %>円</td></tr>
        <tr><th>請求金額合計</th><td class="font-weight-bold"><%= @order.billing_amount %>円</td></tr>
      </table>
    </div>
  </div>
</div>