config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update, :show]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:update]
    resources :order_details, only: [:update]
    resources :works, only: [:update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
get "about" => "public/homes#about"

  scope module: :public do
    root to: "homes#top"
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index,:update,:show,:create,:destroy]
    delete '/cart_items' => 'cart_items#destroy_all'
    post '/orders/comfirm' => 'orders#comfirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light p-3">
        <div class="container">
          <a class="navbar-brand" href="/"><span><strong>ながのCAKE</strong></span></a>
            <!--<li class="navbar-brand">-->
              <%#= link_to root_path do %>
               <!--<img src="" width="200px" height="80px" alt="LOGO(ルートページ)" >-->
              <%# end %>
            <!--</li>-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if request.fullpath.include? "/admin" %>
                <% if admin_signed_in? %>
                  <li>
                    <%= link_to "商品一覧", admin_items_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "会員一覧", admin_customers_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "注文履歴一覧", admin_root_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "ジャンル一覧", admin_genres_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'nav-link text-body btn mx-2' %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to "About", about_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "商品一覧", items_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "新規登録", new_customer_registration_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "ログイン", new_customer_session_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                <% end %>
              <% else %>
                <% if customer_signed_in? %>
                  <li>
                    <%= link_to "マイページ", current_customer, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "商品一覧", items_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "カート", cart_items_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:'nav-link text-body btn mx-2' %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to "About", about_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "商品一覧", items_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "新規登録", new_customer_registration_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                  <li>
                    <%= link_to "ログイン", new_customer_session_path, class:'nav-link text-body btn mx-2' %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class='container-fluid border-top mt-5'>
        <div class='row my-3'>
          <div class='mx-auto'>
            <small>&copy; mmsk 2023</small>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>